---
abstract: 'Download FLV/MP4/SWF files from nicovideo.jp'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-NicoVideo-Download
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0
  CGI::Simple: 0
  Filter::Util::Call: 0
  LWP::UserAgent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
